# **Numpy Tutorial**

## **importing numpy**

In [89]:
import numpy as np

## **Now just testing out numpy and how it works**

### **1D Array**

In [90]:
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


### **2D array**

In [91]:
arr=np.array([[1,2],[5,6]])
arr

array([[1, 2],
       [5, 6]])

In [92]:
print(arr)

[[1 2]
 [5 6]]


### **Attiributes**

In [93]:
np.shape(arr1)

(3,)

### **Need of numpy is for multi dimensional data**

#### **Now to create a multi dimensional array we just need to make a list of list|**

In [94]:
ma=[[1,2,3],
    [4,5,6],
    [7,8,9]]

In [95]:
np.array(ma)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
np.shape(ma)

(3, 3)

In numpy we cannot have inconsitent number of elements like

In [97]:
na=[[1,2],
    [4,5,6],
    [7,8,9]]
na

[[1, 2], [4, 5, 6], [7, 8, 9]]

but in numpy array we get something like 

In [98]:
np.array(na)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

arrays can contain any thing like booleans, decimal, strings

In [ ]:
s=[['Heallo','Konichiwa'],
    ['Bonjour','Hola']]
np.array(s)

array([['Heallo', 'Konichiwa'],
       ['Bonjour', 'Hola']], dtype='<U9')

can contain mixed

In [ ]:
ch=[[1,3],
    [True,4],
    [5,6.0]]
np.array(ch)

array([[1., 3.],
       [1., 4.],
       [5., 6.]])

In [ ]:
ch=[[1,'Hello'],
    [True,4],
    [5,6.0]]
np.array(ch)

array([['1', 'Hello'],
       ['True', '4'],
       ['5', '6.0']], dtype='<U32')

#### **Reshape a array**

In [ ]:
x=[[1,2,3],
   [4,5,6]]
p=np.array(x)
np.shape(p)

(2, 3)

In [ ]:
p.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

can be one dimensional too

In [ ]:
p.reshape(6,)

array([1, 2, 3, 4, 5, 6])

but this doesnot make any sense

In [ ]:
p.reshape(3)

ValueError: cannot reshape array of size 6 into shape (3,)

### **Now a quick way to build numpy arrays**

In [ ]:
np.zeros((3,4))  #3 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:
np.ones((2,3))  #3D array with 2 blocks, 3 rows and 4 columns

array([[1., 1., 1.],
       [1., 1., 1.]])

In [104]:
g=np.arange(1,10)
g.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
np.arange(1,10,2)#low high step

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### **Access Elements in array**