# **Numpy Tutorial**

## **importing numpy**

In [2]:
import numpy as np

## **Now just testing out numpy and how it works**

### **1D Array**

In [3]:
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


### **2D array**

In [4]:
arr=np.array([[1,2],[5,6]])
arr

array([[1, 2],
       [5, 6]])

In [5]:
print(arr)

[[1 2]
 [5 6]]


### **Attiributes**

In [6]:
np.shape(arr1)

(3,)

### **Need of numpy is for multi dimensional data**

#### **Now to create a multi dimensional array we just need to make a list of list|**

In [7]:
ma=[[1,2,3],
    [4,5,6],
    [7,8,9]]

In [8]:
np.array(ma)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.shape(ma)

(3, 3)

In numpy we cannot have inconsitent number of elements like

In [10]:
na=[[1,2],
    [4,5,6],
    [7,8,9]]
na

[[1, 2], [4, 5, 6], [7, 8, 9]]

but in numpy array we get something like 

In [11]:
np.array(na)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

arrays can contain any thing like booleans, decimal, strings

In [12]:
s=[['Heallo','Konichiwa'],
    ['Bonjour','Hola']]
np.array(s)

array([['Heallo', 'Konichiwa'],
       ['Bonjour', 'Hola']], dtype='<U9')

can contain mixed

In [13]:
ch=[[1,3],
    [True,4],
    [5,6.0]]
np.array(ch)

array([[1., 3.],
       [1., 4.],
       [5., 6.]])

In [14]:
ch=[[1,'Hello'],
    [True,4],
    [5,6.0]]
np.array(ch)

array([['1', 'Hello'],
       ['True', '4'],
       ['5', '6.0']], dtype='<U32')

#### **Reshape a array**

In [15]:
x=[[1,2,3],
   [4,5,6]]
p=np.array(x)
np.shape(p)

(2, 3)

In [16]:
p.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

can be one dimensional too

In [17]:
p.reshape(6,)

array([1, 2, 3, 4, 5, 6])

but this doesnot make any sense

In [18]:
p.reshape(3)

ValueError: cannot reshape array of size 6 into shape (3,)

### **Now a quick way to build numpy arrays**

In [19]:
np.zeros((3,4))  #3 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((2,3))  #3D array with 2 blocks, 3 rows and 4 columns

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
g=np.arange(1,10)
g.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.arange(1,10,2)#low high step

array([1, 3, 5, 7, 9])

In [23]:
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### **Access Elements in array**

In [24]:
#Lets take b as our test sample
b=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

okay to acces the row we will be using the indexing thing

In [27]:
b[1] # second row

array([4, 5, 6])

In [28]:
b[0]#first row

array([1, 2, 3])

now for each elements we'll use something like [column,element]

In [37]:
b[0,0]#first column first element

1

In [38]:
b[2,2]

9

now for getting the rows we'll use(:)

In [39]:
b[:] # for getting the whole row

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
b[:,0] # for getting the first column

array([1, 4, 7])

In [36]:
b[:,2]

array([3, 6, 9])

### **Parallel Station**

means operations are independent of each other

we can calcuate maths

In [41]:
b*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

we can do comparison

In [46]:
b>4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

We can use this feature for indexing like

In [49]:
b[b>3]

array([4, 5, 6, 7, 8, 9])

### **Some useful functions**

In [50]:
np.concatenate([b,b+2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])